In [1]:
import torch 
torch.__version__

'2.9.1+cpu'

In [2]:
scalar = torch.tensor(7)
scalar 

tensor(7)

In [3]:
scalar.ndim 

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor([5,3])

In [6]:
vector.ndim

1

In [7]:
vector.shape


torch.Size([2])

In [8]:
matrix = torch.tensor([[5,2],
                       [3,1]])


In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
tensor = torch.tensor([[[3,9,6],
                       [4,8,6],
                       [23,2,1]]])

In [12]:
tensor.ndim

3

In [13]:
tensor.shape

torch.Size([1, 3, 3])

In [14]:
random_tensor = torch.rand(size=(4,5))
random_tensor, random_tensor.dtype

(tensor([[0.7010, 0.3682, 0.4297, 0.9123, 0.1974],
         [0.7236, 0.3998, 0.5250, 0.6047, 0.4045],
         [0.2915, 0.3479, 0.6308, 0.8877, 0.0727],
         [0.7467, 0.3594, 0.4448, 0.3552, 0.5256]]),
 torch.float32)

In [15]:
random_tensor = torch.rand(size=(3,5,4))
random_tensor, random_tensor.dtype

(tensor([[[0.3858, 0.9046, 0.6596, 0.8866],
          [0.8737, 0.8935, 0.5844, 0.7180],
          [0.6121, 0.0878, 0.1719, 0.5075],
          [0.5291, 0.6514, 0.8339, 0.8653],
          [0.7187, 0.5766, 0.9433, 0.0077]],
 
         [[0.1364, 0.1412, 0.7565, 0.0051],
          [0.7613, 0.5716, 0.2764, 0.8604],
          [0.3280, 0.8149, 0.3422, 0.1196],
          [0.6150, 0.6506, 0.3804, 0.7927],
          [0.8874, 0.6342, 0.6390, 0.6960]],
 
         [[0.5176, 0.9761, 0.3221, 0.7084],
          [0.3677, 0.9168, 0.6114, 0.1193],
          [0.1848, 0.4466, 0.3684, 0.0241],
          [0.8836, 0.3900, 0.0644, 0.6318],
          [0.5943, 0.5409, 0.6430, 0.2746]]]),
 torch.float32)

In [16]:
image_tensor = torch.rand(size=(244,244,3))
image_tensor.shape, image_tensor.ndim

(torch.Size([244, 244, 3]), 3)

In [17]:
zeros = torch.zeros(size=(2,3,4))
zeros, zeros.shape, zeros.ndim

(tensor([[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]],
 
         [[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.]]]),
 torch.Size([2, 3, 4]),
 3)

In [18]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [19]:
zero_to_ten = torch.arange(start=0,end=10,step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
zerostwo = torch.zeros_like(zero_to_ten)
zerostwo

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor DataTypes 

In [21]:
float_32_tensor = torch.tensor([3.2,0.5,5,2],
                               dtype = None, #None by default it assumes float32
                               device = None,
                               requires_grad = False # if True, operations performed on the tensor are recorded
                              )
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([4]), torch.float32, device(type='cpu'))

In [22]:
float_64_tensor = torch.tensor([3.2,0.5,5,2],
                               dtype = torch.float64, #None by default it assumes float32
                               device = None,
                               requires_grad = False # if True, operations performed on the tensor are recorded
                              )
float_64_tensor.dtype

torch.float64

## Getting information from tensors 
"what shape are my tensors? what datatype are they and where are they stored? what shape, what datatype, where where where"

In [23]:
some_tensor = torch.rand(3,4,5)
some_tensor.shape, some_tensor.ndim, some_tensor.device, some_tensor.dtype

(torch.Size([3, 4, 5]), 3, device(type='cpu'), torch.float32)

## Manipulating Tensors 

In [24]:
tensor = torch.tensor([1,3,4])
tensor + 10 
tensor * 10

tensor([10, 30, 40])

In [25]:
tensor # performing operations on tensors does not change the initial tensor unless a new value is assgned to it 

tensor([1, 3, 4])

In [26]:
tensor_new = tensor - 1 
tensor_new

tensor([0, 2, 3])

### Matrix multiplication is all you need 

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
-(3, 2) @ (3, 2) won't work
-(2, 3) @ (3, 2) will work
-(3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
-(2, 3) @ (3, 2) -> (2, 2)
-|(3, 2) @ (2, 3) -> (3, 3)

In [27]:
# Element-wise matrix multiplication
tensor * tensor

tensor([ 1,  9, 16])

In [28]:
# Matrix multiplication
torch.matmul(tensor,tensor) # EXAMPLE OF torch.matmul([1*1 + 2*2 + 3*3] = [14])

tensor(26)

### One of the most common errors in deep learning (shape errors)

In [29]:
tensor1 = torch.tensor([[1,2],
                        [3,4],
                        [5,6]],dtype=torch.float32)
tensor2 = torch.tensor([[7,10],
                        [8,11],
                        [9,12]],dtype=torch.float32)
torch.matmul(tensor1,tensor2) 
# This gives an error because the shapes cannot be multiplied
# tensor 1 shape = 3 @ 2
# tensor 2 shape = 3 @ 2 
# correct tensor2 will be of dimension 2 @ 3 

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [30]:
torch.mm(tensor1,tensor2.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor1
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


### Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
print(f"Minimum = {x.min()}")
print(f"Maximum = {x.max()}")
#print(f"Average = {x.mean()}") this will throw an error 
print(f"Average = {x.type(torch.float32).mean()}")
print(f"Total = {x.sum()}")

Minimum = 0
Maximum = 90
Average = 45.0
Total = 450


In [ ]:
y = torch.arange(20,100,5)
y

print(f"Index where maximum value occurs is {y.argmax()}")
print(f"Index where minimum value occurs is {y.argmin()}")

Index where maximum value occurs is 15
Index where minimum value occurs is 0


## Change tensor datatype

In [ ]:
tensor = torch.arange(0,50,10)
print(t1.dtype)

torch.int64


In [ ]:
tensor_float32 = tensor.type(torch.float32)
tensor_float32.dtype

torch.float32

## Reshaping, stacking, squeezing and unsqueezing¶

In [ ]:
# Create a tensor
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
# Change view (keeps same data as original but changes view)
z = x.view(1, 7)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])
